function setup() {
    //check if user is logged in
    firebase.auth().onAuthStateChanged(user => {
        if (user) { //if user logged in
            insertNameFromFirestore();
            getBookmarks(user);
        } else {
            console.log("User is not logged in.")
            window.location.href = "index.html";
        }
    })
}

setup();

// Get the user's name from Firestore and insert it into the page
function insertNameFromFirestore() {
    //check if user is logged in
    firebase.auth().onAuthStateChanged(user => {
        if (user) { //if user logged in
            console.log(user.uid)
            db.collection("users").doc(user.uid).get().then(userDoc => {
                console.log(userDoc.data().name)
                userName = userDoc.data().name;
                console.log(userName)
                document.getElementById("name-goes-here").innerHTML = userName;
            })
        }
    })
}

// Get the array of bookmarks from the user's document
function getBookmarks(user) {
    db.collection("users").doc(user.uid).get()
        .then(userDoc => {

            // Get the Array of bookmarks
            var bookmarks = userDoc.data().saved;
            console.log(saved);

            // Get pointer the new card template
            let newcardTemplate = document.getElementById("savedCardTemplate");

            // Iterate through the ARRAY of bookmarked hikes (document ID's)
            saved.forEach(thisTip => {
                console.log(thisTip);
                db.collection("Tips and Tricks").doc(thisTip).get().then(doc => {
                    var title = doc.data(); // get value of the "name" key
                    var docID = doc.id;  //this is the autogenerated ID of the document

                    //clone the new card
                    let newcard = newcardTemplate.content.cloneNode(true);

                    //update title and some pertinant information
                    newcard.querySelector('.card-title').innerHTML = title;
                    newcard.querySelector('.card-text').innerHTML = "This is a test";
                    //Finally, attach this new card to the gallery
                    savedCardGroup.appendChild(newcard);
                })
            });
        })
}